### PR TITLE
Misc improvements

### PR DESCRIPTION
**Pull request by gunnarmorling**
Hey @mincong-h first batch of some changes. I hope these things make sense, check out the issue descriptions, too. Just let me know if anything is unclear.

### CODE REVIEW

**Comment by mincong-h** [comment]
Hi, Gunnar. Your review speed is impressive, thanks for the PR !! I'll
check this tonight :)

**Comment by gunnarmorling** [comment]
@mincong-h Pushed on more commit to this PR.

**Comment by mincong-h** [comment]
@gunnarmorling , I need to learn how to merge the code... I just clicked the merge button without knowing what's happening. It should be done in my desktop instead of the web browser, too 😢 .

**Comment by gunnarmorling** [comment]
The merge itself looks good, you can see the history here: https://github.com/mincong-h/gsoc-hsearch/network

Usually we work with rebases rather than merges in Hibernate, but using the merge is fine for the time being. To transfer the changes to your local machine, just run

```
git pull origin master
```

("origin" being the name of the Git remote you configured). Let me know if you need further help.

**Comment by mincong-h** [comment]
I knew that it had been merged successfully, but I want the title of commit respect the naming convention : 

```
#xxx summary of the merge / commit
```

capture

At the same time I feel confused about
- difference between `pull` and `fetch`.
- When you sent your PR, il should be a PR from your `gunnarmorling/master` branch to my origin/master branch, right ? But if I want to handle the PR locally (on my Mac), then what's happening ? Because I'm using local/master on my Mac. Is it : 
  - pull (or fetch) the `origin/master` to `local/master`
  - PR become `gunnarmorling/master` to `local/master`
  - handle PR locally
  - push to origin
  - PR is considered as done

You don't need to reply me for this, Gunnar. I just need some time and exercise to figure it out. Since this is not the priority, I'll learn it a little bit later.

**Comment by gunnarmorling** [comment]
> I knew that it had been merged successfully, but I want the title of commit respect the naming convention

Yes, that's the issue with using the merge functionality on GitHub. I'll describe the approach I use below.

Some answers:
- difference between pull and fetch.

Fetch will get all the changes from the remote repo to your local one. But they are not applied to any local branches. E.g. if remote/master is ahead of local/master by two commits, git fetch will "download" the two commits, but local/master will remain unchanged. You then could do `git merge origin/master` (if origin is the name of your remote) and it will apply the changes without any futher remote operation.

`git pull origin/master` will download and apply the changes right away.

> When you sent your PR, il should be a PR from your gunnarmorling/master branch to my origin/master branch, right 

Usually it's better to work from feature branches in the fork. I.e. my pull request will be from gunnarmorling/some-feature-branch to mincong-h/master.

> But if I want to handle the PR locally (on my Mac), then what's happening

Here is what I do and what I recommend:
- `git remote add gunnarmorling git@github.com:gunnarmorling/gsoc-hsearch.git` (Registers my fork on GitHub as a remote repo for your local repo; only needed once)
- `git checkout -b gunnarmorling_some-feature-branch (creates a local branch for taking my changes)
- `git rebase master` (rebases my changes on top of your local master, in case you've been working on other stuff since I've created the PR)
- Test/Review
- git checkout master (switch to master)
- git merge gunnarmorling_some-feature-branch (merges my changes into master; As you've done the rebase before, this will be a "fast-forward merge", meaning no actual merge commit is needed, but rather the commits can be added right on top to master
- git push origin master (push your local master, including my changes, to your remote on GitHub)
- git branch -d gunnarmorling_some-feature-branch (deletes that local feature branch)

**Pull request merged**
